services:
  db:
    image: postgres
    container_name: postgres_lifeplaylist
    restart: always
    volumes:
      - ./postgres-lifeplaylist-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: postgres_flask_lifeplaylist
      POSTGRES_USER: linpinhung
      POSTGRES_PASSWORD: linpinhung
    ports:
      - "5434:5432"


  flask:
    build: 
      context: .
      dockerfile: flask.Dockerfile
    container_name: flask_lifeplaylist
    restart: always
    volumes:
      - .:/app
    environment:
      - APP_NAME=FlaskApp
      # - FLASK_DEBUG='on'
      # - FLASK_APP=./app.py
    expose:
      - 8080
    depends_on:
      - db 


  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_lifeplaylist
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask