"""add_testt_migrate_col

Revision ID: 404a5903a775
Revises: 7fc56165753e
Create Date: 2021-07-12 11:50:32.749954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404a5903a775'
down_revision = '7fc56165753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('test_migrate_col', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'test_migrate_col')
    # ### end Alembic commands ###
